// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyf-CfcbboVnqcG11N3SZU_TYYbNKwTsU',
    appId: '1:624041347257:web:a219c9aef9f73e6ea8b368',
    messagingSenderId: '624041347257',
    projectId: 'teubicamos-ebbd2',
    authDomain: 'teubicamos-ebbd2.firebaseapp.com',
    storageBucket: 'teubicamos-ebbd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj-ZSHvPMwdickBHDceXRm-JKU319nSIc',
    appId: '1:624041347257:android:752e6c8f496232fca8b368',
    messagingSenderId: '624041347257',
    projectId: 'teubicamos-ebbd2',
    storageBucket: 'teubicamos-ebbd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCEI7qwKK6s8KDqr7GXJAs0vFmkoEUTuY',
    appId: '1:624041347257:ios:76a53768e97e41e4a8b368',
    messagingSenderId: '624041347257',
    projectId: 'teubicamos-ebbd2',
    storageBucket: 'teubicamos-ebbd2.firebasestorage.app',
    iosBundleId: 'com.example.teUbicamos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCEI7qwKK6s8KDqr7GXJAs0vFmkoEUTuY',
    appId: '1:624041347257:ios:76a53768e97e41e4a8b368',
    messagingSenderId: '624041347257',
    projectId: 'teubicamos-ebbd2',
    storageBucket: 'teubicamos-ebbd2.firebasestorage.app',
    iosBundleId: 'com.example.teUbicamos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyf-CfcbboVnqcG11N3SZU_TYYbNKwTsU',
    appId: '1:624041347257:web:d32f6c0c0e3835fba8b368',
    messagingSenderId: '624041347257',
    projectId: 'teubicamos-ebbd2',
    authDomain: 'teubicamos-ebbd2.firebaseapp.com',
    storageBucket: 'teubicamos-ebbd2.firebasestorage.app',
  );
}
